INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE) VALUES(1, 'USD', 10000.0);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE) VALUES(2, 'USD', 20000.0);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE) VALUES(3, 'USD', 30000.0);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE) VALUES(4, 'USD', 40000.0);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE) VALUES(5, 'USD', 50000.0);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE) VALUES(6, 'USD', 60000.0);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE) VALUES(7, 'USD', 70000.0);